version: '3.8'

services:
  # База данных для Auth
  auth_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5441:5432" # Прокидываем на 5441, чтобы не конфликтовать с локальной БД

  # База данных для Todo
  todo_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5442:5432"

  # Сервис авторизации
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - auth_db
    restart: always
    environment:
      - DB_HOST=auth_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - JWT_SECRET=your_super_secret_key

  # Сервис задач
  todo_service:
    build:
      context: .
      dockerfile: todo_service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - todo_db
      - auth_service
    restart: always
    environment:
      - DB_HOST=todo_db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=todo_db
      - JWT_SECRET=your_super_secret_key